### ISSUE TITLE
Swift Language Version 4.2

### ISSUE THREAD

**Issue by j-bylund** [Adyen/adyen-barcoder-ios#13]
In the project, Swift Language version is set to
SWIFT_VERSION = 4.0
(looks like 4 in the IDE)
but now it is using some Swift 4.2 constructs, so building the project fails, with errors like
```
AdyenBarcoder/Barcoder.swift:124:36: error: 'willEnterForegroundNotification' has been renamed to 'NSNotification.Name.UIApplicationWillEnterForeground'
            forName: UIApplication.willEnterForegroundNotification,
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   NSNotification.Name.UIApplicationWillEnterForeground
UIKit.UIApplication:28:22: note: 'willEnterForegroundNotification' was introduced in Swift 4.2
    public class let willEnterForegroundNotification: NSNotification.Name
```

The fix would be to set SWIFT_VERSION to 4.2.
Do you prefer issues for things like this, or a PR?

**Comment by diegomarcon** [comment]
Hi @j-bylund,

Thanks for reporting the issue. 

I'll update the project and release a new version asap.

**Comment by diegomarcon** [comment]
Hi @j-bylund,

1.4.1 is released with the fix for swift version on the root project.

Cheers,
