### ISSUE TITLE
Crash in accessoryDidConnectNotification

### ISSUE THREAD

**Issue by Bojan7B** [Adyen/adyen-barcoder-ios#2]
Application sometimes crashes in Barcoder library:

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x18291af70 objc_msgSend + 16
...
5  ExternalAccessory              0x191688b58 -[EAAccessory description] + 380
6  AdyenBarcoder                  0x100bc949c specialized AccessoryStreamer.accessoryDidConnectNotification(NSNotification) -> () (AccessoryStreamer.swift:154)
7  AdyenBarcoder                  0x100bc69e4 @objc AccessoryStreamer.connect(EAAccessory) -> () + 52
8  CoreFoundation                 0x183e6ab10 
...
23 UIKit                          0x189dec534 UIApplicationMain + 208
24 $AppName           0x100115ff8 main (main.m:16)
25 libdispatch.dylib              0x182d8d5b8 (Missing)

**Comment by diegomarcon** [comment]
Closing issue as it's related to #4.
